config/routes.rb
KayakWeather::Application.routes.draw do
  
  root to: 'weather#local' 
  
  match 'cities', to: 'weather#cities', as: 'cities'
  match 'get_hot_spots', to: 'weather#get_hot_spots', as: 'get_hot_spots'
  match 'get_city_latlng', to: 'weather#get_city_latlng', as: 'get_city_latlng'

end

app/models/distance.rb
class Distance < ActiveRecord::Base

  # *** ASSOCIATIONS *** #
  belongs_to :origin, class_name: 'Place', foreign_key: 'origin_id'
  belongs_to :destination, class_name: 'Place', foreign_key: 'destination_id'
  
  # *** ATTR_ACCESSIBLE *** #
  attr_accessible :origin_id, :destination_id, :value 

end

app/models/place.rb
class Place < ActiveRecord::Base

  # *** ASSOCIATIONS *** #
  has_many :distances
  has_many :destinations, through: :distances
  
  # *** ATTR_ACCESSIBLE *** #
  attr_accessible :name, :lat, :lng
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  
  #
  # Method: get_hot_spots
  # -------------------------------------------------
  # Returns the top ten hot spots from the origin and
  # distance requested.
  #
  def get_hot_spots
    
    @hot_spots = []
    @origin = Place.find(params[:place])
    @distance = params[:distance]
    
    # GET PLACES WITHIN REQUESTED DISTANCE FROM ORIGIN
    
    places = []
    if params[:geonamesAPI] == 'true'
      ##   USE GEONAMES API   ##
      rad = (@distance.to_i * 1.60934).to_s # Converting miles to kilometers
      geoResponse = Geonames.getPlaces(@origin.lat, @origin.lng, rad, "1000")
      geoList = geoResponse['geonames']
      
      # SAMPLING (DETERMINISTIC, EVEN DISTRIBUTION)
      numGeos = geoList.length
      limit = 100
      
      # Checks if number of returned places is large
      if numGeos > limit
        c = (numGeos*1.0)/limit
        for i in 0..(limit-1)
          index = (c*i).to_i # Index for sampled place
          gn = geoList[index]
          places << Place.new(name: gn['name'], lat: gn['lat'].to_s, lng: gn['lng'].to_s)
        end
      else 
        for gn in geoList
          places << Place.new(name: gn['name'], lat: gn['lat'].to_s, lng: gn['lng'].to_s)
        end
      end
    else
      ##   USE DATABASE   ##
      places << @origin
      distances = Distance.where('origin_id = ? AND value <= ?', @origin, @distance)
      for d in distances
        places << d.destination
      end
    end

    # GET 7-DAY FORECASTS FOR ALL PLACES
    
    forecasts = []
    id = 0 # API KEY ID - Used to alternate between multiple api keys to reduce response time
    for p in places
      fcResponse = Weatherbug.getForecast(p.lat, p.lng, id)
      fcList = fcResponse['forecastList']
      id = (id + 1) % 8
      for fc in fcList
        if !fc['high'].blank?
          forecasts << Forecast.new(p.name, p.lat, p.lng, fc['dateTime'], fc['high'].to_i)
        end
      end
    end
    
    # GET TOP 10 HOT SPOTS
    
    if forecasts.length > 10
      tenth = get_ith_warmest(forecasts, 10)
      for f in forecasts
        if f >= tenth
          @hot_spots << f
        end
      end 
    else
      for f in forecasts
        @hot_spots << f
      end
    end
    
    # SORT HOT SPOTS
    
    @hot_spots.sort! { |x, y| y <=> x }

    respond_to do |format|
      format.js
    end
    
  end
  
  #
  # Method: get_city_latlng
  # -------------------------------------------------
  # Returns the latitude and longitude of requested city
  # in JSON. Used for Google Map city marker positioning.
  #
  def get_city_latlng
    
    city = Place.find(params[:id])
    latlng = {lat: city.lat.to_f, lng: city.lng.to_f}
    respond_to do |format|
      format.json { render json: latlng }
    end
    
  end
  
  private 
  
    #
    # Method: get_ith_warmest
    # -------------------------------------------------
    # Implementation of the worst-case O(n) median of medians
    # selection algorithm. It selects the ith warmest forecast
    # in an unsorted array. ( i = 10 in our case )
    #
    def get_ith_warmest(array, i)
      # Base case
      if array.length <= 5
        array.sort! { |x, y| y <=> x }
        array[i-1]
      else
        median = get_median(array)
        low = []
        high = []
        
        # Partitioning array based on median-of-medians
        for elem in array
          if elem < median
            low << elem
          elsif elem > median
            high << elem
          end
        end
        
        # Recursive call         
        k = high.length + 1 # k is the rank of median-of-medians 
        if i > k
          get_ith_warmest(low, i - k) 
        elsif i < k
          get_ith_warmest(high, i)
        else
          median
        end
      end
    end
    
    #
    # Method: get_median
    # -------------------------------------------------
    # Helper method for getting the median of an unsorted
    # array. It divides the array into subsets of 5 elements
    # each, computes the medians of those subsets, and recursively
    # gets the median of those medians.
    #
    def get_median(array)
      numElems = array.length
      if numElems <= 5
        array.sort! { |x, y| y <=> x }
        array[((numElems+1)/2) - 1]
      else 
        medians = []
        index = 0
        while index < numElems do
          set = []
          count = (numElems - index >= 5) ? 5 : numElems - index 
          count.times { |j| set << array[index + j] }
          set.sort! { |x, y| y <=> x }
          medians << set[((count+1)/2) - 1]
          index += count
        end
        get_median(medians)
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KAYAK - Hot Spots Near Your Destination</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/k.ico' %>
</head>
<body <%= yield :onload %>>

<%= yield %>

</body>
</html>

app/views/weather/_head.html.erb
<a id="logo" href="http://www.kayak.com">
  <img id="logoimg" width="187" height="43" alt="KAYAK - Travel Deals - Cheap flights and hotels" src="http://cdn2.kayak.com/v534174/images/kayak-logo.png">
</a>
<div id="headermaintabs">
  <a id="hot-spots-link" <% if page == 'local' %> class="navselected" <% end %> href="/">Local</a>
  <a id="hot-spots-link" <% if page == 'cities' %> class="navselected" <% end %>href="/cities">Cities</a>
</div>

app/views/weather/_hot_spots.html.erb
<div class='hs_header'>
  <%= origin.name %> | <%= distance %> Miles
</div>
<div class='hs_links'>
 <span class='hs_marker_link'><%= link_to 'Show', 'javascript:showHotSpotMarkers()' %></span> |
  <span class='hs_marker_link'><%= link_to 'Hide', 'javascript:clearHotSpotMarkers()' %></span>
</div>
<% count = 1 %>
<% for hs in hot_spots %>
  <div class='hs_elem'>
    <div class='hs_elem_marker'>
      <% num = count.to_s %>
      <% num = '0' + num if count < 10 %>
      <%= image_tag "http://google-maps-icons.googlecode.com/files/yellow" + num + ".png" %>
    </div>
    <div class='hs_elem_info'>
      <div class='hs_elem_name'>
        <%= link_to hs.name, 'javascript:clearHotSpotMarkers(' + count.to_s + ')' %></a>
      </div>
      <div class='hs_elem_date'>
        <%= Time.at(hs.dateTime/1000).strftime('%b %d, %A') %>
      </div>
    </div>
    <div class='hs_elem_temp'>
      <%= hs.temp %><span class='hs_elem_temp_unit'>°F</span>
    </div>
  </div>
<% count += 1 %>
<% end %>

app/views/weather/_left.html.erb
<div id='hot_spots_form_wrapper'>
  <%= form_tag get_hot_spots_url, method: :get, id: :hot_spots_form do %>
          
  <div id="city-input-field">
    <% cities_array = [['', 0]] %>
    <% cities_array += Place.order(:name).map { |city| [city.name, city.id] } %>
    <label class="fieldLabel">Destination</label>
    <a id="city-input-wrapper" class="dropdown-wrapper dropdown defaultSelect">
      <span id="city-input-status" class="dropdown-status"></span>
      <span class="dropdown-icon"></span>
      <%= select_tag :city, options_for_select(cities_array, 248), class: 'dropdown-select'  %>
    </a>
  </div>
        
  <div id="distance-input-field">
    <div id="distance_header">
      <label id="distance_label" class="fieldLabel">Distance</label>
      <div id="distance_value">
        <%= text_field_tag :distance %>
        <label id="distance_unit" class="fieldLabel">miles</label>
      </div>
    </div>
    <div id='distance-slider'></div>
  </div>
        
  <button id="hot_spots_submit_button" class="ui-button ui-button-huge" type="submit">
    <span>Find Hot Spots</span>
  </button>
  
  <% end %>
  
</div>
<div id="map_canvas" style="width:600px; height:500px"></div>

app/views/weather/_right.html.erb
<div id='virgin_promo'>
  <div id='feature_explanation'>
    <% if page == "local" %>
      The <span class="feature_title">Local</span> feature satisfies the challenge requirements.
      Distance can be adjusted up to 30 miles, based on your search needs.<br/><br/>
      If the number of places returned by the Geonames API is large,
      the application deterministically selects 100 places among them by using a simple sampling method.
      This sampling was installed for two purposes:<br/><br/>
      
      (2) Ensure an even distribution of close/distant places from the origin<br/><br/>
      (1) Reduce Weatherbug API calls and prevent QPS restriction blockage<br/><br/>
      
      Setting a small maxRows value for the Geonames API parameter will <b>only return the closest places, 
      regardless of the radius value</b>. This is because the returned places are sorted by distance from the origin.
      For example, a call with radius=30 miles and maxRows=20 will most likely return places 
      that are only a few miles away from the origin. For the same case, my sampling will first receive max 1000
      places (which is sufficient in most cases for radius=30 miles) and then choose 20 places that are more evenly spread across
      the request boundary.
    <% elsif page == "cities" %>
      The <span class="feature_title">Cities</span> feature is a spinoff of the original challenge requirements, which was inspired from
      identifying two problems with the Geonames API:<br/><br/>
      (1) It limits radius to <b>300km</b>(much shorter than the original 500 miles)<br/><br/>
      (2) It doesn't support a call that returns <b>only cities</b> for nearby places<br/><br/>
      I solved these two problems by creating my own database of cities and the distances between them.
      Unlike <span class="feature_title">Local</span>, the Geonames API is not used in <span class="feature_title">Cities</span> and instead, data comes directly from the application's database.<br/><br/>
      I used GeoNames.org resource <%= link_to 'cities15000.txt', 'http://download.geonames.org/export/dump/', target: '_blank'%>
      as the data source and wrote a Java parser to retrieve data for major cities, which I defined as having a population of 100K or more. (<%= link_to 'Parser source code', 'https://github.com/yeaz/KayakWeather/blob/master/PlaceParser.java', target: '_blank' %>)<br/><br/>
      In my opinion, <span class="feature_title">Cities</span> is a more useful tool than <span class="feature_title">Local</span> from a user's perspective, because there is much more variation in temperature when dealing with a larger distance. In real life, it makes more sense to
      see the differences in temperature on a regional level rather than a local level.
    <% end %>
  </div>
</div>
<div id='loading_wrapper' style="display:none">
  <div id='loading_message'>Please wait momentarily,<br> We are searching for nearby hot spots</div>
  <%= image_tag 'loading.gif', alt:'Loading...' %>
</div>
<div id='result'></div>

app/views/weather/cities.html.erb
<% content_for :onload do %>
  onload="initializeMap(5)" 
<% end %>
<div id='fixedWidthOuter'>
  <div id='hd'>
    <%= render partial: 'weather/head', locals: { page: 'cities' } %>
  </div>
  <div id='bd'>
    <div id='bd-main' class='bdMain'>
      <div class="fdMainLeft">
        <%= render partial: 'weather/left' %>
      </div>
      <div class="fdMainRight">
        <%= render partial: 'weather/right', locals: { page: 'cities' } %>
      </div>
    </div>
  </div>
</div>

<script type='text/javascript'>
   
  $(document).ready( function() {
  
    $( "#distance-slider" ).slider({
      range: "min", 
      min: 0,
      max: 500,
      value: 500,
      step: 10,
      slide: function( event, ui ) {
        $( "#distance" ).val( ui.value );
        cityCircle.setRadius(ui.value * 1609.34);
      }
    });
    $( "#distance" ).val( $( "#distance-slider" ).slider( "value" ) );
    
    $('#hot_spots_form').submit( function() {
      $('#result').empty();
      clearHotSpotMarkers();
      if ($('#virgin_promo').length) {
        $('#virgin_promo').fadeOut( function() { 
          $('#virgin_promo').remove();
          processSubmit(false);
        });
      } else {
        processSubmit(false);
      }
      return false;
    });
    
  });

</script>

<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?sensor=false&region=US">
</script>

app/views/weather/get_hot_spots.js.erb
<% if @hot_spots.blank? %>
$('#result').html("<div class='error_msg'>There are no major cities near <div class='error_msg_city'> <%= @origin.name %></div> within <%= @distance %> miles</div>");
<% else %>
$('#result').html("<%= escape_javascript(render partial:'weather/hot_spots', locals: { hot_spots: @hot_spots, origin: @origin, distance: @distance }) %>");
<% i = 0 %>
<% for hs in @hot_spots %>
hotSpotMarkers[<%= i %>].setVisible(true);
hotSpotMarkers[<%= i %>].setPosition(new google.maps.LatLng(<%= hs.lat.to_f %>, <%= hs.lng.to_f %>, false));
<% i += 1 %>
<% end %>
<% end %>

app/views/weather/local.html.erb
<% content_for :onload do %>
  onload="initializeMap(9)" 
<% end %>
<div id='fixedWidthOuter'>
  <div id='hd'>
    <%= render partial: 'weather/head', locals: { page: 'local' } %>
  </div>
  <div id='bd'>
    <div id='bd-main' class='bdMain'>
      <div class="fdMainLeft">
        <%= render partial: 'weather/left' %>
      </div>
      <div class="fdMainRight">
        <%= render partial: 'weather/right', locals: { page: 'local' } %>
      </div>
    </div>
  </div>
</div>

<script type='text/javascript'>
   
  $(document).ready( function() {
    
    $( "#distance-slider" ).slider({
      range: "min", 
      min: 0,
      max: 30,
      value: 30,
      step: 1,
      slide: function( event, ui ) {
        $( "#distance" ).val( ui.value );
        cityCircle.setRadius(ui.value * 1609.34);
      }
    });
    $( "#distance" ).val( $( "#distance-slider" ).slider( "value" ) );
  
    $('#hot_spots_form').submit( function() {
      $('#result').empty();
      clearHotSpotMarkers();
      if ($('#virgin_promo').length) {
        $('#virgin_promo').fadeOut( function() { 
          $('#virgin_promo').remove();
          processSubmit(true);
        });
      } else {
        processSubmit(true);
      }
      return false;
    });
    
  });

</script>

<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?sensor=false&region=US">
</script>